export const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
export const ROLE_ADMIN = 'ADMIN';
export const ROLE_OPERADOR_BACKOFFICE = 'OPERADOR_BACKOFFICE';
export const ROLE_POS_ADMIN = 'POS_ADMIN';
export const ROLE_POS_SELLER = 'POS_SELLER';

export const ROLES = [
  ROLE_SUPER_ADMIN,
  ROLE_ADMIN,
  ROLE_OPERADOR_BACKOFFICE,
  ROLE_POS_ADMIN,
  ROLE_POS_SELLER,
] as const;
